version: "3.9"

services:
  carfax-backend:
    container_name: carfax-backend
    image: nikita/carfax-backend:latest
    env_file:
      - ./src/local.env
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    hostname: mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - PUID=1000
      - PGID=1000

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf

volumes:
  mongodb-data:
